### ISSUE TITLE
SKIM64 not installing

### ISSUE THREAD

**Issue by ghost** [Kaldaien/FAR#108]
I've downloaded SKIM64 as well as installed all the prerequisites and I'm still having issues getting SKIM64 to install fixes (with all its games but I'm mostly interested in Nier Automata/FAR atm).

Here are the screenshots of how an installation plays out
[SKIM64 at the start of installation](https://imgur.com/cglbgom)
[SKIM64 downloading files](https://imgur.com/dcx2AUv)
[Nier Automata directory during installation](https://imgur.com/jPV4iSS)
[Nier Automata folder after 'installation'](https://imgur.com/jGWwqpa)
[SKIM64 after 'installation'](https://imgur.com/saAzcrQ)

It doesn't matter if run SKIM64 as admin or not, it always fails to install FAR.

These are the [installer.log](https://pastebin.com/PVpKHS9C) and [installed.ini](https://pastebin.com/NH8G2eRL) files SKIM64 produces.

**Comment by lazycrypt** [comment]
Did some browsing through the Steam forums and one of the suggestions was to temporarily disable antivirus softwarel. I've tried doing that with Windows Defender (only AVS I have) but unfortunately SKIM64 did the same thing as above and failed to install FAR.

**Comment by Idearum** [comment]
Just download and extract the archive manually instead: https://github.com/Kaldaien/FAR/releases/download/far_070/FAR_0_7_0_23.7z

Remember to disable or decline the update check on launch. It gets triggered since it doens't actually know what version you're running, but since you're running the latest version you can just ignore it.

Also note that issues on GitHub isn't monitored by Kaldaien. You should preferably use the main thread over on his Steam Community Group for fastest help.
