### ISSUE TITLE
Freezing during gameplay

### ISSUE THREAD

**Issue by xXBlackBulletXx** [Kaldaien/FAR#110]
Everytime I play the game, after a little bit the game freezes and i can't play anymore. Any solution? Thanks

**Comment by Idearum** [comment]
Post your logs to pastebin.com and link them here.

**Comment by xXBlackBulletXx** [comment]
steam_api.log:  [https://pastebin.com/2Vc6aKYR](url)
ReShade64.log: [https://pastebin.com/JhbR7B56](url)
modules.log: [https://pastebin.com/0C4vXcgR](url)
game_output.log: [https://pastebin.com/h5KJcKWm](url)
dxgi_budget.log: [https://pastebin.com/VjgKBnQ7](url)
dinput8.log: [https://pastebin.com/FtunHPG9](url)
CEGUI.log: [https://pastebin.com/YHEZWeWg](url)
that's all? Thanks for help

**Comment by Idearum** [comment]
You mentioned in the other thread that you experienced freezes even without FAR installed; is this correct? Because if so then it does not have anything to do with FAR, and I urge you instead to remove FAR completely all files and folders until only these remain: https://steamuserimages-a.akamaihd.net/ugc/808804068655852551/1CC119D2F8F8A2C2AD9519FA15027333A263C31D/

After that you should probably validate game cache in Steam, followed by starting to shut down applications etc that might be interfering with the game (antivirus/malware protection suites, RTSS/Afterburner, overlay applications, etc) until you find whatever might be causing it.

And ensure your computer and drivers are updated as well!
