### ISSUE TITLE
Is multiplayer\coop possible to implement?

### ISSUE THREAD

**Issue by Riconec** [Kaldaien/FAR#111]
Hi. I am wondering is it possible to create mod with multiplayer or coop (any kind) to play with friends?

I saw some games without any ideas of multiplayer from the developers, but later mod community releases such kind of mod. Yes, it was limited, but possible.

What do you think?

Thanks in advance!

**Comment by drdaxxy** [comment]
In principle you can make multiplayer mods for *any* PC game. But it's a huge undertaking - designing a multiplayer mode and developing the servers and netcode is enough work on its own, and for multiplayer mods you need to do very broad and detailed analysis of the game engine given only released binaries.

It's the sort of thing that happens if somebody (or a group of people) with the interest *and* the skills *and* the time decides to spend weeks if not months of it on a passion project. Not because someone asked for it.

I can't see it working well with NieR: Automata's setting and premise either.

It's also completely off-topic for the bug tracker of a project called "Fixes Automata Resolution"...
