### ISSUE TITLE
Thoughts about crashes on pirated game copies

### ISSUE THREAD

**Issue by LBYPatrick** [Kaldaien/FAR#144]
Hi all,

I am thinking about not to call any methods in ``steam_api.h`` when having non-genuine game copies since all piracy groups bypasses steam DRM by having awful emulators, and these emulators might not support all steam features since it was only for bypassing purposes.

I really wanted to modify the code to make this happen (Since I have experience with C++) but there is no way for telling whether the user is pirating the game and ``SpecialK`` is not open-source, so I was not able to make it work without manual user configuration.

> I do own NieR: Automata on steam, but years ago I was pirating this game

**Comment by Idearum** [comment]
Special k is open-source, but because of the fradulent reports of pirates the GitHub repository was taken down. The source code is now hosted on GitLab: https://gitlab.com/Kaldaien/SpecialK

As for disabling Steam API related enhancements, that functionality is already built into FAR, but not obvious since Kaldaien have never gotten around to renaming it.

Open dinput8.ini, scroll down to [Steam.Log] and change Silent=false to Silent=true. This will disable all use of the Steam API related enhancements, including the Steam API DLL validation check that fake emulators fall over on.

**Comment by LBYPatrick** [comment]
Then...Should we put this piece of information in README?
