### ISSUE TITLE
Crash on Startup - Indeterminate Cause

### ISSUE THREAD

**Issue by biomatter** [Kaldaien/FAR#150]
I installed FAR via SKIM and now the game won't start :( Most recent crash log attached. I looked through them myself, but tbh they're a little dense.

This is probably unrelated, but before I installed FAR the problem I was having was that the game won't stay fullscreen.

[05-27-2019__08'51'36.zip](https://github.com/Kaldaien/FAR/files/3224538/05-27-2019__08.51.36.zip)

**Comment by Idearum** [comment]
You seem to experience the same issue that [this user is experiencing](https://steamcommunity.com/app/524220/discussions/0/1651045226213920156/).

No idea what's up with that. Seeing how the two of you both are using Nvidia mobile GPUs it might have something to do with that though? Have you updated Windows recently?

Otherwise I'd recommend trying out the steps mentioned in the linked thread, and possibly try older versions and see if they work better.

**Comment by apflu** [comment]
Or maybe the same problem as i experienced? #123

**Comment by biomatter** [comment]
You guys are fast! I'm surprised at how on top of things you are, given that the game is now almost (more than?) two years old.

I tried everything in order, and it was apflu's problem / solution that ended up working for me. I replaced the dinput8.dll with the SPECIALK64.dll and now I don't crash on start-up, FAR is responsive, and the game stays fullscreen without being petulant. Thank you both so much for the timely support!

Oh, and for posterity's sake, before I forget: one problem I had that prevented me from noticing the fix was working was that I was launching the game through the Steam UI. However, running the executable directly worked. Maybe there was something in the read-me telling me to bypass Steam, but I might have missed it.
