### ISSUE TITLE
[0.7.0.23] Trying to open configuration menu quits the game (no crash folder created)

### ISSUE THREAD

**Issue by sidewinder94** [Kaldaien/FAR#155]
Hi, 

I tried today to update FAR from version 0.7.0.22 to 0.7.0.23.

When I tried to open the configuration menu afterwards (Ctrl+Maj+Backspace) the game instantly quits.

In the logs folder, no "crash" folder is created.

I've rolled back to version 0.7.0.22 for the time being.

Might be a duplicate of #107 

At your disposal if you need to get more info.

**Comment by Idearum** [comment]
Here's the download link to FAR v0.7.0.22: https://github.com/Kaldaien/FAR/releases/download/far_070/FAR_0_7_0_22.7z

Downgrading might work. If it prompts you regarding updating, just decline it (there's no real difference between the two versions).

If it still crashes, remove or rename the CEGUI folder that's located in the game folder as well as possibly in your Documents\My Mods\SpecialK folder. If you're not using a global injection of Special K (Kaldaien's tool for injecting the underlying Special K mod into Steam games), you can delete the whole SpecialK folder as well.

I don't know if this is the cause, but we did have a couple of times where the mod would crash due to weird encoding on the config files, hence removing the whole SpecialK folder would fix that as the folder and files were recreated with the proper text encoding.

**Comment by sidewinder94** [comment]
Well, i did already roll back.

I don't have the global injector installed either.

Documents\My Mods\SpecialK doesn't exist on my computer (maybe it IS the issue)
