### ISSUE TITLE
Wine/Proton?

### ISSUE THREAD

**Issue by xorrizon** [Kaldaien/FAR#163]
Hi, any way to get this working with wine/proton & DXVK?
The mouse cursor always resetting to the center of the screen when using a controller is driving me crazy.....

**Comment by weter11** [comment]
It's working with master DXVK starting with https://github.com/doitsujin/dxvk/commit/079cda1c0ce225be3db68a39383de47904e67cfd, no more massages "No video memory'. If you do not want to compile itself, binary at https://git.froggi.es/doitsujin/dxvk/pipelines?page=1&scope=finished. But mod work very bad at least on my hardware.
First of all, on that gist page they did not notice that you need to disable nvapi, nvapi64 in winecfg. Without it game stuck with a window:
![Снимок экрана_2020-04-07_20-35-20](https://user-images.githubusercontent.com/14630689/78897534-03b54980-7a7b-11ea-9c72-f1a89a61361d.png)
Secondly on my hardware only FAR 0.5.x.x work. All newer versions (0.7.x.x) stuck on black screen with beep from MGS4. And not all functions work with FAR, only [FAR.Lighting] & [FAR.FrameRate] & without CEGUI (I simply rename folder), so no any interface ingame, only configuring in ini files.
And configuring is enough for me, but mod generate 0.5MiB every second log with only one error:
`warn:  D3D11Buffer::QueryInterface: Unknown interface query
warn:  6f15aaf2-d208-4e89-9ab4-489535d34f9c`
And use 35% of my 4C/8T core i5 instead of 10-15% w/o mod, so FPS ingame can't past 20-25 FPS, GPU load from 100% fall to 40-50%, with option GlobalIlluminationWorkgroups=0, GPU load fall to 25-28%, but FPS the same.
And the most important mod didn't load folder with HD textures.
Maybe that error because something is not installed, but on FAR README page no any word about dependencies. Maybe someone find what dependencies it need.

**Comment by Idearum** [comment]
These are the prerequisites of FAR. Note that they're a list written for Windows users:


```
Operating System	Package
All			Visual C++ 2017 Redistributable [install both x86 and x64]
x64: 			https://go.microsoft.com/fwlink/?LinkId=746572 (direct download, open in your browser)
x86: 			https://go.microsoft.com/fwlink/?LinkId=746571 (direct download, open in your browser)
All			DirectX End-User Runtime[www.microsoft.com] (most likely already installed)
Windows 7		KB2670838[www.microsoft.com] (aka Platform Update)
Windows 7		KB2533623[support.microsoft.com] (aka Security Advisory 2269637)
```

**Comment by weter11** [comment]
Hm, all is installed. As I know winetricks always install x86 and x64. So, I tried 0.6.2.15 for testing purposes and ... CPU usage drop to 10-15%, NieRAutomata_d3d11.log for 5 mins generate only 2MiB and game works, performance is ok! All is ok now except "GPUnity's Texture Pack". In [Textures.D3D11] Inject=true.
And now another error instead:
`warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  b18b10ce-2649-405a-870f-95f777d4313a
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  d0223b96-bf7a-43fd-92bd-a43b0d82b9eb`
And this one:
`err:   D3D11Device::SetExceptionMode: Not implemented`
First in DXGI, second in DXVK.

**Comment by RealTehreal** [comment]
If I understand the above comments, it's all about ARC Linux. Is there a way to make it work under Ubuntu?

**Comment by weter11** [comment]
My system is Xubuntu 19.10. Wait for stable 20.04 release for update.

**Comment by ItsRogueRen** [comment]
Are there instructions for something like this with the Tales of Berseria buttons? (installing PS4 controller buttons)
