### ISSUE TITLE
Stuck in Cutscene Mode with FPS Uncapper Enabled

### ISSUE THREAD

**Issue by Velgus** [Kaldaien/FAR#24]
Occasionally while playing with the FPS Uncapper enabled, the game will fail to exit cutscene mode correctly. When it happens, it leads to strange behavior, and prevents progression in my experiences. Restarting the game and disabling the FPS Uncapper fixes it.

This has happened to me in two instances so far:
1. The cutscene in path A right before firing the mortar at the giant machine. It gave me control of 2B, but it was still in cutscene mode, so it would not let me interact with the mortar. FAR 0.4.0.3.
2. During the opening mission of Path B, right after the cut-scene where 9S flies upwards after hacking the four points. The enemies were appearing and attacking, but it was staying in the cutscene mode and I could not move, attack, or take damage. FAR 0.4.1.1.

My specs give me a frame rate that averages 120-144 (max for my monitor) in interior scenes like that, so the unlocked frame rate is being taken advantage of if that matters.

**Comment by SkacikPL** [comment]
Can confirm - encountered same issue.

**Comment by TyroneSama** [comment]
Confirming that cutscene mode sticks during the opening of Route B.

**Comment by pikajude** [comment]
Confirming that I also get stuck in the mortar sequence

**Comment by Idearum** [comment]
So possibly "cutscene mode" would need to be limited to 60 FPS as well to prevent these issues from occurring.

**Comment by SkacikPL** [comment]
It's not just cutscenes, it's also possible to get stuck in some of the dialogues. It happened to me during end of the parade escort. I was unable to close the dialog, going back to 60 fps after you're locked does not help.

**Comment by Idearum** [comment]
Yeah, I know. The problem is that all of those scenarios need a good way to detect them happening through the memory. If I'm not mistaken that's what took the original FPS unlock mod the most time, to find reliable memory addresses that could be used to detect the current state of the game (e.g. hacking game etc).

So the mod basically needs a way to detect cutscenes AND dialogues (or, really any form where scripting takes place) and then limit to 60 FPS around those events.
