### ISSUE TITLE
Versioning Scheme (in)sanity

### ISSUE THREAD

**Issue by Link-Satonaka** [Kaldaien/FAR#28]
Your releases page has many releases per release(?!), including an unversioned release in every release.

How am I supposed to know which one is the right one to download? If I had to guess, you issue the first release file FAR.7z with no version, then abuse filenames to create minor patch versions atop that release.

Releases are releases, minor fixes are new releases, and all filenames should always include what version they are.

**Comment by Link-Satonaka** [comment]
It also looks like in the very first release you've included an automated installer, only to be found by those who know where it is.

Why not link to that in the README.md you should probably create?

**Comment by Kaldaien** [comment]
Yes, that is correct. FAR.7z is the initial release. I have minor corrective releases too.

I actually ask that people never link directly to my GitHub repository, because this is just for tracking issues and releasing software. The Steam forums are where I have all of the documentation for my projects, I find the Guide system on Steam superior to having a Wiki on GitHub.

Likewise, you don't have to mess with the point releases, the mod has an auto-updater, and `version.ini` handles all of that stuff for you.

**Comment by Link-Satonaka** [comment]
Alright, thanks for clearing that up.
