### ISSUE TITLE
Will this patch create "FAR.ini"?

### ISSUE THREAD

**Issue by AmanoTouko** [Kaldaien/FAR#29]
Actually I don't really know how to use this patch.
I've heard someone said that this patch will create a file named "FAR.ini".
And I can change the value of  Global Illumination Workgroups.
But it didn't.So can someone tell me how to use this patch?
many thanks.

**Comment by Kaldaien** [comment]
This is the URL you should have been given, I never link people directly to my GitHub repositories because I don't like its documentation system (and broken Markdown).

http://steamcommunity.com/app/524220/discussions/0/135512104777399045/

I usually have guides, but for this project it's just a single thread post.
