### ISSUE TITLE
Why this appeared and can't be solved

### ISSUE THREAD

**Issue by yorkzhy** [Kaldaien/FAR#33]
![qq 20170415123922](https://cloud.githubusercontent.com/assets/14953362/25060809/ce90002c-21d8-11e7-8091-ba9b3265341f.png)

**Comment by Kaldaien** [comment]
The first several errors are caused by GeForce Experience, the nvspcap service for streaming games to Shield devices. That thing is evil :) The second is some stupid debug information the developer decided to print.

This doesn't need to be solved, it just prints all debug output from any third-party software. If you see stuff there, usually it's from software of questionable quality. At least that's been my experience.
