### ISSUE TITLE
Can't click accept on the SLA prompt/It doesn't disapear. 

### ISSUE THREAD

**Issue by sobi123** [Kaldaien/FAR#43]
The Software agreement stays on top no matter what I do. I can briefly (1sec) make it disappear by ctrl+shift+O, but it comes back every time and makes it impossible to play. Funnily enough the prompt disappears (but not the HUD) when I go off screen, or change focus to another app while windowed.

Have to say that I get a vibration on the controller when I click accept, and the button is highlighted but it never goes through.

Is there a way to disable it in the config file ? if so which option and in which file is it ?

Also I have manually installed FAR latest ver (0.5.6 [Patch Fix] - 5/8/17)

**Comment by 424778940z** [comment]
LOL, this is the prove of people never read agreement.

**Comment by jaychew90** [comment]
same here. I've gone through the whole list but still can't click accept.

**Comment by marcussacana** [comment]
try set the value silent to false
![https://u.nya.is/kulzms.png](https://u.nya.is/kulzms.png)
if works, the reason it's because you have the pirate version of the nier.

**Comment by Kaldaien** [comment]
Sorry, but will you kindly take your discussion of piracy elsewhere. There's apparently a chap who is maintaining a branch for you pirates. I don't know if he'll be even half as curious to you as I would be if you weren't trying to drag me into something illegal. I'd love to help you, but you've gotta go through legal channels.

**Comment by marcussacana** [comment]
@Kaldaien a sincere question, Why do this? If you really wanted to stop the pirates, you would not have been able to run the mod with silent = true, and you'd probably start using DRMs / stop refreshing the source, of course, if you really wanted to get in the way. You're more of a bitch, are not you?
We are a community, we should not be fighting with each other, of course I am a mere pirate talking about ethics / morals, you would probably think so. But I'm really intrigued by the way you act ...
Why ?, Why do you imply with the pirates but in the end does not stop them altogether?
I also noticed some issues fix that you said you would not fix.
(srry my google tl eng)

**Comment by marcussacana** [comment]
Ohh sorry, bitch is a error from google, really sorry.

**Comment by Robblle** [comment]
@marcussacana Because nobody who purchased the game legally cares about the DRM. Also pirating in 2017 LUL. Stop complaining if you pirated the game. Yes, pirates don't have a voice in this.

Sorry for my little rant. I guess this issue will be closed.

**Comment by Kaldaien** [comment]
@marcussacana: Who said I want to stop pirates. I do not want all of my time and effort destroyed by them.

If you're going to do something illegal, have the decency to do it with a modified version of my software that I have no affiliation with. Why is this so difficult for you pirates to understand?

**Comment by marcussacana** [comment]
í see, thx for reply.

**Comment by sobi123** [comment]
@jaychew90 Downloading the 0.5.6.1 from here sorted me out, now I can enjoy the game in all it's 17FPS glory ! (Intel HD4000)

**Comment by Kaldaien** [comment]
@marcussacana: I don't know why I'm even telling you this, but I disassembled the DXGI DLL you are distributing in binary-only form (I don't care about the license violation to be honest and I'm sure you don't either), but you've removed some things that are in no way shape or form malicious and designed to prevent the software from crashing.

You should really provide your source code modifications, because you're going to crash the game for people and they will no doubt want to fix these problems. I won't be the one to do it, but it's food for thought. There are a number of things wrong with binary-only distribution, but that's your biggest problem. Hopefully you make it clear to your users you don't care about the stability of their game, because you're kind of punishing them in an ironic way.

**Comment by marcussacana** [comment]
@Kaldaien Thanks for the warning, frankly I do not remember having changed anything besides the PirateAhoy function and preventing the users install updates from your git,
Before push i test into the cracked nier and retail, 
I recive a request before but i don't rebuild the mod, i patch it from the x64dbg and to proxy the auto-update , I just searched and changed your git url with a hex editor. (I use ver.ini instead of version.ini, it's because the length of the original string is short)
I don't rebuild because actually, i use the vs15, and my c++ build tools it's outdated...
so i thought "more easy just patch"...
if possible, you can say what version into my git i have patched the wrong code?
---
In response to your consideration, I will restore the readme (this is what i can do :/),
I'm sorry for formulating a wrong opinion about you just by what I read into some forum, really.

**Comment by DAOWAce** [comment]
> I'm sorry for formulating a wrong opinion about you just by what I read into some forum,
> And if it's just this... hahaha It seems like the world thinks in you the wrong way.

Hence why everyone who uses Kaldaien's mods started defending him of their own volition.

All the BS spewed over those crackwatch reddit threads is extremely aggravating to even read myself, and I barely know him! The "pirate compatible" version's responses proved people don't have a damn clue about anything and are just witch hunting someone.. which is why the threads were locked.

But no matter what anyone says, they believe what they believe.  Ignorance in its finest form.

**Comment by marcussacana** [comment]
you think? i just understanded: by technical reason we can't use a resource of the mod with cracks, if try, we the game can work unstable; I'm not defending with something like "hey!, corrupt the game it's right!", but if he put a code to auto-detect the cracked version and disable the specifed resource he is helping the piracy directally, and this, he don't want.

this is what i understanded, and if this is true he isn't this too bad how everyone are saying.
