### ISSUE TITLE
Can't install Special K

### ISSUE THREAD

**Issue by KAD11** [Kaldaien/FAR#44]
Tried installing both the FAR mod and Special K through the auto-install on steam. FAR seems to install, but when I try to install Special K, it gives me an install pending pop-up that says it will install when I run a steam game. When I try to run Nier, it plays the M.G.S.  detected sound and doesn't run. I'm new to installing mods, so is there something I need to do first, or am doing wrong?

**Comment by Idearum** [comment]
What product to you want to use, exactly? FAR or Special K (the global injector)?

* If it's FAR, then install it manually. There's a [guide](https://steamcommunity.com/sharedfiles/filedetails/?id=914437196) over on the Steam Guide section on how to do so.

* If it's the global injector Special K, then you should really download and install it from the [Special K](https://github.com/Kaldaien/SpecialK/releases) repository. The latest version work in an entirely different way nowadays and requires that you manually run inject.bat and uninject.bat to start and stop the injection. The global injector have gone through various changes recently, so I'm not even sure if the automated installer works for it either.

**Comment by Kaldaien** [comment]
Sorry, I have corrected this.

FAR was not installable because `version.ini` was deleted while I had no control over my own end-user support page. I did not want users installing the product using the instructions on Steam followed by absolutely no way to contact me. Very few of them understand issue tracking and other nuances of GitHub.

**Comment by KAD11** [comment]
Thanks, I got FAR working.
