### ISSUE TITLE
Crashes With OBS

### ISSUE THREAD

**Issue by coinpop** [Kaldaien/FAR#50]
Like the title says, running the game with FAR normally and everything's fine, but as soon as I start up OBS and it begins capturing the game, then there's the Metal Gear alert sound and crashes.
Wasn't an issue beforehand, have streamed a good few hours of it already with OBS, hasn't crashed until just recently.
I dunno how to get any logs or anything if it'd help

**Comment by Kaldaien** [comment]
Can you provide logs/dxgi.log the next time it happen?

These logs are available if you open the config UI and select File | Browse Logs

**Comment by coinpop** [comment]
dxgi: https://pastebin.com/ET84ztz3
crash: https://pastebin.com/wcQ2B4Y9

**Comment by coinpop** [comment]
Like I said, only crashes when OBS is capturing the game for about 5 seconds, I can recreate the crash incredibly consistently, but without OBS no issues

**Comment by Kaldaien** [comment]
Testing fixes will be particularly difficult right now because GitHub has shutdown the Special K repository :-\

However, looking at your log, I actually see this, which looks like more of a problem than OBS:

    05/12/2017 21:43:13.243: [DLL Loader]   ( rzdspsrv.dll                 ) loaded '                                                        d3d9.dll' <LoadLibraryW> { '' }

I'm _guessing_ that's some Razer software. The fact that it's loading d3d9.dll will not help anything, other software that's loaded after it will see D3D9 and D3D11 and the chances of a crash go way up depending on how well the other software can figure out what's really being used for rendering. This is the reason my own software has options to turn hooks for specific graphics APIs off.

OBS doesn't have those options to the best of my knowledge, it may be confused by whatever rzdspsrv needs d3d9 for :)

**Comment by coinpop** [comment]
Yeah, just ran it without Razer Synapse open, and OBS capturing and it was fine, so it definitely seems like it's those two -together- is the issue, not each one on it's own. Apparently a couple other games have issues with Synapse and OBS together, so I guess for now I'll just close Synapse if I plan on using OBS.

**Comment by Kaldaien** [comment]
Alright, I guess it's about time I pickup some Razer software and try to fix problems it creates ;)

For years I've been aware that it does all sorts of weird things, but since I don't use any Razer hardware just sort of shrugged it off. MSI Nahimic used to cause similar weird problems but I picked up an MSI laptop and spent a lot of time debugging that product before finally fixing it.

Aside from the Razer problem, is OBS working correctly for you? Early on in the project many people were complaining about OBS compatibility problems. I don't think I ever directly addressed those, but nobody's complained recently (aside from this).

**Comment by coinpop** [comment]
At first it was a bit finicky, only real issue is occasionally the capture will have the image of the game frozen, primarily if it starts capturing before that first blank screen that says "loading" right before the main menu, and if I remember right, using alt+enter to make it fullscreen or windowed. But if I wait until it loads the main menu and then have it capture afterward it's fine.
