### ISSUE TITLE
HUD-less screenshot option doesn't hide mini-map

### ISSUE THREAD

**Issue by Fironet** [Kaldaien/FAR#60]
It seems the feature to take HUD-less screenshots doesn't hide the mini-map in Nier: Automata. I've rebound the key to several other buttons while testing and it produces the same result. Frequently the captures also contain the full HUD.

Is this a limitation of the game or something on my side? I'm running FAR with MSI Afterburner (with Riva set to not cap the framerate since FAR does it for me) for its video capture ability, but I've also tried without it running and it produces the same result.

Tried to search for results but most of the discussion seems to have been deleted from the Steam pages. Thanks for any insight into this. Running the original version of Nier with the latest FAR.

**Comment by Kaldaien** [comment]
There's a 5 frame capture delay before the HUD is shown again. For whatever reason, the Steam overlay is _extremely_ late on your system.  Usually you figure about a 2-3 frame delay due to driver render-ahead, I can't explain why your system's an additional 2 frames behind.

I could add an option to increase the number of frames the HUD is hidden for. The only thing I can think of is that the game uses quad-buffering by default. You may want to change BufferCount to 1 (double-buffering) or 2 (triple-buffering). This will decrease input latency.

**Comment by Fironet** [comment]
> You may want to change BufferCount to 1 (double-buffering) or 2 (triple-buffering). This will decrease input latency.

So I tried with the `BackBufferCount` set to `1` and `2` in the dxgi.ini but the same problem, unfortunately.

What could affect the delay timing? I'm using a popular Steam skin named 'Air' (the so-called 'Classic' version of it), would that account for any difference?
