### ISSUE TITLE
[FAR 0.6.2.10]Can not open the game

### ISSUE THREAD

**Issue by tkp206093** [Kaldaien/FAR#80]
0.6.2.9 is can open the game but 0.6.2.10 can not open the gane

I think is the dxgi.dll,Because I change dxgi.dll 0.6.2.10 to 0.6.2.9 is can open

[dxgi.txt](https://github.com/Kaldaien/FAR/files/1138157/dxgi.txt)
[modules.txt](https://github.com/Kaldaien/FAR/files/1138156/modules.txt)

**Comment by Kaldaien** [comment]
This is your problem:

```07/11/2017 16:19:51.309: [ Module ]  ( 000000003B400000h + 00086016 )                                                                              D:\Games\NieR Automata(TM)\steam_api64.dll```

**Comment by Looov3** [comment]
Kaldaien, could you please share your SCID and VERSION resources of your original steam_api64.dll? I have the same issue on a pirate version so this may work I think

**Comment by Idearum** [comment]
> Kaldaien, could you please share your SCID and VERSION resources of your original steam_api64.dll? I have the same issue on a pirate version so this may work I think

Huh? There's a reason why the mod validates the SteamAPI file, since it heavily relies upon it. Every single fake Steam API DLL file that have been thrown at the mod have caused crashes all over the place.

If you're so eager to bypass a legitimate safety check and run the mod with unsupported products then fork the code and remove the check yourself, but understand that you'll obviously get no support by doing so.

The only version of the game that is supported is the legitimate copy.

**Comment by Looov3** [comment]
Thank you, I'm already using patched version and it works clearly. Great thanks to you for developing the original mod, it really increased my FPS
